name: nexora
description: "Nexora - A modern developer news and bookmarking app built with Flutter and Clean Architecture"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Navigation
  go_router: ^17.0.0

  # Environment Variables
  flutter_dotenv: ^6.0.1

  # Code Generation
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # Network
  dio: ^5.9.2

  # Local Storage
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^10.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Cone Generation
  riverpod_generator: ^2.6.5
  build_runner: ^2.5.4
  freezed: ^3.1.0
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  assets:
    - .env 
